name: Production CI/CD Pipeline

on:
  workflow_dispatch:

jobs:
  test-and-build:
    name: Build & Push Container
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Metadata(Tags/Labels)
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=raw,value=latest
            type=raw,value=${{ github.sha }}
      
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy:
    name: Deploy to Production
    needs: test-and-build
    runs-on: ubuntu-latest

    steps:
      - name: Downcase Repo Name
        id: string
        run: |
          echo "repo=${GITHUB_REPOSITORY,,}" >> $GITHUB_OUTPUT

      - name: Remote SSH command execution
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.GCP_VM_HOST }}
          username: ${{ secrets.GCP_VM_USER }}
          key: ${{ secrets.GCP_SSH_PRIVATE_KEY }}
          script: |
            docker pull ghcr.io/${{ steps.string.outputs.repo }}:latest
            
            docker stop aggregator-app || true
            docker rm aggregator-app || true

            docker image prune -f

            docker run -d \
            --name aggregator-app \
            --restart unless-stopped \
            -p 80:80\
            -e DB_URL="${{ secrets.DB_URL }}" \
            -e TELEGRAM_BOT_TOKEN="${{ secrets.TELEGRAM_BOT_TOKEN }}" \
            -e TELEGRAM_CHAT_ID="${{ secrets.TELEGRAM_CHAT_ID }}" \
            -e POLL_INTERVAL="${{ secrets.POLL_INTERVAL }}" \
            -e RATELIMIT_SECONDS="${{ secrets.RATELIMIT_SECONDS }}" \
            ghcr.io/${{ steps.string.outputs.repo }}:latest